import os
import subprocess


def generate_documentation_if_needed():
    # Path to the Doxygen output directory
    doxygen_dir = "../doxygen"
    doxygen_html_dir = "../doxygen/html"
    doxygen_config_file = "../doxygen/Doxyfile"

    # Check if the documentation is already generated by looking for index.html
    index_html_path = os.path.join(doxygen_html_dir, "index.html")

    if not os.path.exists(index_html_path):
        print("Documentation not found. Generating now...")

        # Run the Doxygen command
        try:
            subprocess.run(["doxygen", doxygen_config_file], cwd=doxygen_dir, check=True)
            print("Documentation generated successfully.")
        except subprocess.CalledProcessError as e:
            print(f"An error occurred while generating the documentation: {e}")
    else:
        print("Documentation already exists. No need to generate.")



